### ISSUE TITLE
Errors in test suite(pending) and `getUnixTime`(resolved in 0.4.6) results for windows

### ISSUE THREAD

**Issue by jneira** [kazu-yamamoto/unix-time#54] opened 2019-06-04 19:01 UTC
Hi, testing and trying to fix the package build for win 7, we found that:
* The test suite fails in windows ( windows 7 and 10, cabal-2.4.1.0, ghc-8.6.5):
```console
Test suite spec: RUNNING...

UnixTime
  formatUnixTime
    behaves like the model FAILED [1]
  parseUnixTimeGMT & formatUnixTimeGMT
    inverses the result
      +++ OK, passed 100 tests.
    inverses the result (2) FAILED [2]
  addUnixDiffTime & diffUnixTime
    invrses the result
      +++ OK, passed 100 tests.
  UnixTime Storable instance
    peek . poke = id
      +++ OK, passed 100 tests.

Failures:

  test\\UnixTimeSpec.hs:44:13:
  1) UnixTime.formatUnixTime behaves like the model
       Falsifiable (after 4 tests):
         UnixTime {utSeconds = 1635071885, utMicroSeconds = 542638}
       expected: "Sun, 24 Oct 2021 12:38:05 +0200"
        but got: "Sun, 24 Oct 2021 12:38:05 "

  To rerun use: --match "/UnixTime/formatUnixTime/behaves like the model/"

  test\\UnixTimeSpec.hs:53:9:
  2) UnixTime, parseUnixTimeGMT & formatUnixTimeGMT, inverses the result (2)
       Falsified (after 4 tests):
         UnixTime {utSeconds = 1635071885, utMicroSeconds = 542638}

  To rerun use: --match "/UnixTime/parseUnixTimeGMT & formatUnixTimeGMT/inverses the result (2)/"
```
* Otoh The value of `utSeconds` returned  by `getUnixTime` seems to be incorrect. The program:
```haskell
module Main where

import Data.UnixTime
import qualified GHC.IO.Encoding
import qualified System.IO

main = do
  GHC.IO.Encoding.setLocaleEncoding System.IO.utf8
  putStrLn "Testing unix time"
  t <- getUnixTime
  let t' = UnixTime {  utSeconds = 4294967295, utMicroSeconds =999999 }
  putStrLn . show $ t
  m <- formatUnixTime mailDateFormat t
  putStrLn . show $ m
  putStrLn . show $ t'
  m' <- formatUnixTime mailDateFormat t'
  putStrLn . show $ m'
```
has this output
```console
Testing unix time
UnixTime {utSeconds = 207173602136727, utMicroSeconds = 48236}
"?, -1 ? 1899 -1:-1:-1 "
UnixTime {utSeconds = 4294967295, utMicroSeconds = 999999}
"Sun, 07 Feb 2106 07:28:15 +0100"

```

**Comment by jneira** [comment] 2019-06-04 19:29
[The test suite in appveyor for fix-win7 has succeded](https://ci.appveyor.com/project/kazu-yamamoto/unix-time/builds/25041195) with stack and ghc-8.6.3 so maybe it depends on cabal/ghc versions?

**Comment by sighingnow** [comment] 2019-06-05 10:59
@jneira Are your working on 32bit win7 or 64bit win7?

**Comment by jneira** [comment] 2019-06-05 13:56
64 bits for both windows 7 and 10

**Comment by jneira** [comment] 2019-06-05 22:23
I cant test it with stack, it throws an error that sometimes is throwed by cabal too:
```
PS D:\dev\ws\haskell\unix-time> stack test
unix-time-0.4.5: build (lib + test)
Preprocessing library for unix-time-0.4.5..
Building library for unix-time-0.4.5..
Preprocessing test suite 'spec' for unix-time-0.4.5..
Building test suite 'spec' for unix-time-0.4.5..
Linking .stack-work\dist\e626a42b\build\spec\spec.exe ...
D:\dev\ws\haskell\unix-time\.stack-work\dist\e626a42b\build/libHSunix-time-0.4.5-IBIazFuQIJnJhbGD18ZUwr.a(strptime.o):strptime.c:(.text+0x1064): referencia a `timegm' sin definir
collect2.exe: error: ld returned 1 exit status
`gcc.exe' failed in phase `Linker'. (Exit code: 1)
....
```
Using stack-1.9.3, default project stack.yaml, windows 10
When cabal throws the error is due a bad config.h generation in the configure step: the default `config.h.in` definitions are not replaced by the values computed in configure.

**Comment by sighingnow** [comment] 2019-06-06 01:12
Just FYI: I couldn't reproduce the test failure on Windows 10 64bit, with ghc-8.6.3 (lts-13.4).

**Comment by sighingnow** [comment] 2019-06-06 01:28
I could see a test failure using 32-bit ghc on windows 10 (64bit system). But it isn't the same with you and it isn't related to locale. The failure is because the value `4294967295` in the test has already succeed the range of `Int` for 32-bit compiler, thus the failure is expected.

https://github.com/kazu-yamamoto/unix-time/blob/cdfda676dcc1ee84b3de5dca4a48945f2d6b6e10/test/UnixTimeSpec.hs#L26-L34

As for your failure about the string `"?, -1 ? 1899 -1:-1:-1 "`, I think it might caused by the locale of your machine. Could you please provide more detailed information about your system ? Especially the locale  settings (language, country, etc.) and the result of `chcp` command?

**Comment by jneira** [comment] 2019-06-06 06:31
Mmm, it seems to me that the error is caused by the incorrect output of `getUnixTime` cause if i build a reasonable value, like the generated by the Arbitrary instance the output of `formatUnixTime`is correct:

* With `utSeconds = 4294967295` the formatted output is `Sun, 07 Feb 2106 07:28:15 +0100`
* With `utSeconds = 207173602136727` the output is `?, -1 ? 1899 -1:-1:-1`

The last one is clearly incorrect cause is too big for actual time and exceed the size of `Word32` used in windows to store the value.

I've test directly `gettimeofday` compiling a c program:
```c
#include <stdio.h>
#include <time.h>
#include <sys/time.h>

int main()
{
  struct timeval tv;
  time_t nowtime;
  struct tm *nowtm;

  gettimeofday(&tv, NULL);
  nowtime = tv.tv_sec;
  printf("Now is %ld\n",nowtime);
  printf("Size of timeval: %d %d %d",
         sizeof(tv.tv_sec), sizeof(tv.tv_usec), sizeof(tv));
}
```

```
# which gcc
/path/to/ghc-8.6.5/mingw/bin/gcc
# gcc -o test.exe -fno-stack-protector test.c
```
An then, in dos console:
```
D:\path\tol\unix-time>test
Now is 1559801928
Size of timeval: 4 4 8
```
Afaiu the size of the struct matches the used ones by `Sys.hsc`
```haskell
foreign import ccall unsafe "gettimeofday"
    c_gettimeofday :: Ptr CTimeVal -> Ptr CTimeZone -> IO CInt

getUnixTime :: IO UnixTime
getUnixTime = allocaBytes (8) $ \ p_timeval -> do
{-# LINE 28 "Data\\UnixTime\\Sys.hsc" #-}
    throwErrnoIfMinus1_ "getClockTime" $ c_gettimeofday p_timeval nullPtr
    sec  <- ((\hsc_ptr -> peekByteOff hsc_ptr 0))  p_timeval
{-# LINE 30 "Data\\UnixTime\\Sys.hsc" #-}
    usec <- ((\hsc_ptr -> peekByteOff hsc_ptr 4)) p_timeval
{-# LINE 31 "Data\\UnixTime\\Sys.hsc" #-}
    return $ UnixTime sec usec
```

My locale in windows is `es` and i use in my dos console `chcp 65001`.

**Comment by jneira** [comment] 2019-06-06 10:28
I've done some more tests with the same wrong results:
* using mingw64 shipped with stack: `msys2-20180531` and `msys2-20150512` (instead my mingw local installation)
* using `ghc-8.6.3` instead `8.6.5`
* both with `cabal init sandbox && cabal install && cabal run` and `cabal new-run`

**Comment by sighingnow** [comment] 2019-06-06 11:00
It is impossible to use values that larger than `maxBound :: Word32`. I have asked the mingw guys about the field types of `struct timeval`[see 1]. The test case using `utSeconds = 207173602136727` is expected to fail. On 64bit Windows, the `CTime` is 64bit, but we cannot pass this value to C code, see also the note in `instance Storable UnixTime`.

https://github.com/kazu-yamamoto/unix-time/blob/cdfda676dcc1ee84b3de5dca4a48945f2d6b6e10/Data/UnixTime/Types.hsc#L41-L55

1: https://sourceforge.net/p/mingw-w64/bugs/720/

**Comment by jneira** [comment] 2019-06-06 22:27
@sighingnow thanks for the point
I think i've got the cause of the bug. This code:
```haskell
getUnixTime = allocaBytes (#const sizeof(struct timeval)) $ \ p_timeval -> do
    throwErrnoIfMinus1_ "getClockTime" $ c_gettimeofday p_timeval nullPtr
    sec  <- (#peek struct timeval,tv_sec)  p_timeval
    usec <- (#peek struct timeval,tv_usec) p_timeval
    return $ UnixTime sec usec
```
is compile by `hsc2hs` in
```
sec' <- ((\hsc_ptr -> peekByteOff hsc_ptr 0))  p_timeval
```
The [`peekByteOff`](http://hackage.haskell.org/package/base-4.12.0.0/docs/Foreign-Storable.html#v:peekByteOff) functions read bytes from memory with a pointer and an offset. What how many bytes are readed? As many as the target type can hold, in this case CTime which has a size of 8 bytes. So `peekByteOff` reads those 8 bytes which is the size of the entire struct!

If we restrict the reading to a `Word32` of 4 bytes like the `Storable` instance for `UnixTime` already does, the output starts to be correct:
```haskell
sec' <- ((#peek struct timeval,tv_sec)  p_timeval) :: IO Word32
let sec = fromIntegral sec'
```
Output
```
Testing unix time
UnixTime {utSeconds = 1559859562, utMicroSeconds = 783512}
"Fri, 07 Jun 2019 00:19:22 "
UnixTime {utSeconds = 4294967295, utMicroSeconds = 999999}
"Sun, 07 Feb 2106 07:28:15 +0100"
```

**Comment by jneira** [comment] 2019-06-07 06:07
Well, so only left the test errors in the roundtrips between parsing and formatting.
If you watch the output after patching `getUnixtime` and the test error you can note that milliseconds are not printed. I think that is the main cause of the failing tests. 
It could be related with locale handling although the output is the same using `_create_locale` (in windows 10) or using an empty locale (in windows 7)

**Comment by sighingnow** [comment] 2019-06-07 08:30
It is strange that the first call didn't get correct timezone offset but the second call does. I think the issue is about the `localtime_r`, which calls `localtime_s`, rather than the locale issue.

I couldn't reproduce the failure on 64bit windows 10, even using empty locale. @jneira Could you help me check the value of `t->tm_isdst` [here][1] for both calls?

[1]: https://github.com/kazu-yamamoto/unix-time/blob/a9ac887c5b58b84fa841dba884860ae14233c197/cbits/strftime.c#L495

**Comment by jneira** [comment] 2019-06-09 20:50
Hi, sorry for the delay, i've added a `printf("t->tm_isdst= %d\n", t->tm_isdst)` and the result was: `t->tm_isdst= 1` (the expected, isnt?)

**Comment by jneira** [comment] 2019-06-09 21:16
The case escapes in https://github.com/kazu-yamamoto/unix-time/blob/a9ac887c5b58b84fa841dba884860ae14233c197/cbits/strftime.c#L525, no `TM_GMTOFF` or `ALTZONE` defined.

**Comment by jneira** [comment] 2019-06-09 22:40
But `_timezone` is defined to `3600` (but when using it prints the timezone incorrect `+0100` instead `+0200`)

**Comment by jneira** [comment] 2019-06-12 05:29
Anyway it is strange that the two issues were not reproduced in other windows envs other that mine (with both windows 7 and 10) and @ruomad one (windows 7?), like appveyor or @sighingnow windows 10. Maybe finding the cause of that could help to fix the issue. :thinking:

**Comment by sighingnow** [comment] 2019-06-12 05:51
It is quite strange that it cannot be reproduced at other windows 7.

I think we could release a new version now since we have already fixed the "unknown symbol" issue (#51) and the `getUnixTime` bug (#55) and it is still unclear about how to fix this issue.

@kazu-yamamoto Could you please send a new release to hackage?

**Comment by jneira** [comment] 2019-06-12 07:17
Ok, another test, i've been able to run the executable with `stack-1.9.3` under dos console:

```haskell
main = do
  GHC.IO.Encoding.setLocaleEncoding System.IO.utf8
  putStrLn "Testing unix time"
  t <- getUnixTime
  let t' = UnixTime {  utSeconds = 4294967295, utMicroSeconds =999999 }
  putStrLn . show $ t
  m <- formatUnixTime mailDateFormat t
  z <- formatUnixTime "%Z" t
  z' <- formatUnixTime "%z" t
  putStrLn . show $ m
  putStrLn . show $ z
  putStrLn . show $ z'
  
  putStrLn . show $ t'
  m' <- formatUnixTime mailDateFormat t'
  putStrLn . show $ m'
```
with output:
```console
X:\ws\haskell\unix-time>stack run
Testing unix time
UnixTime {utSeconds = 1560323377, utMicroSeconds = 670005}
"Wed, 12 Jun 2019 09:09:37 "
"Hora de verano romance"
""
UnixTime {utSeconds = 4294967295, utMicroSeconds = 999999}
"Sun, 07 Feb 2106 07:28:15 +0100"
```
Notes:
* The UnixTime created manually prints the time zone, although an incorrect one (`+0100` instead `+0200`)
```
# date -R
Wed, 12 Jun 2019 09:17:19 +0200
```
* The UnixTime extracted with `getUnixTime` doesnt print the time zone (`%z`), but prints `%Z`

**Comment by jneira** [comment] 2019-06-12 07:20
> @kazu-yamamoto Could you please send a new release to hackage?

Agree, taking in account that #51 are blocking the install of downstream packages and tools in windows 7

**Comment by kazu-yamamoto** [comment] 2019-06-13 03:16
A new version has been released.

**Comment by sighingnow** [comment] 2019-06-16 15:33
After setting the locale of my windows 10 to `Europe/Madrid` I can see what is going wrong with `%z`. The timezone `Europe/Madrid` has "day saving time" during summer. For `UnixTime {utSeconds = 4294967295, utMicroSeconds = 999999}`, the date is in Feb and `+0100` is the correct timezone. For `UnixTime {utSeconds = 1560323377, utMicroSeconds = 670005}` the date is in `Jun` and `tm_isdst` is `1`, and previous implementation assumes it cannot decide the correct timezone offset and print out nothing.

Now everything is ok after #56:

```
main :: IO ()
main = do
  let t1 = UnixTime { utSeconds = 1560323377, utMicroSeconds =670005 }
  print =<< formatUnixTime "%Y-%m-%d %H:%M:%S %z" t1
  let t2 = UnixTime { utSeconds = 4294967295, utMicroSeconds =999999 }
  print =<< formatUnixTime "%Y-%m-%d %H:%M:%S %z" t2
```

```
"2019-06-12 09:09:37 +0200"
"2106-02-07 07:28:15 +0100"
```

The fix is inspired by https://github.com/python/cpython/blob/45e0411eee023b21acf1615e995d26058d66c0f1/Modules/timemodule.c#L1578-L1582

**Comment by jneira** [comment] 2019-06-16 19:23
wow, good catch and quick fix, congrats @sighingnow

**Comment by ruomad** [comment] 2019-06-17 07:41
Hello,
I can confirm that it works allright in my win7 setup.
Thank you very much for this very nice work !
Bruno

Bruno DAMOUR

**Comment by sighingnow** [comment] 2019-06-17 17:08
@ruomad Thanks for confirming that. I have pushed a new commit to #56 and fixed an out-of-index bug in C code. Now CI is green as well.

Waiting for merging and next release!

**Closed** 2019-06-17 23:43 UTC
